# Project-wide Gradle settings.
# Augmentation de la mémoire pour éviter que le Daemon ne plante
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# Accélère la compilation en permettant de compiler plusieurs modules en même temps
org.gradle.parallel=true

# Active le cache de configuration pour des builds plus rapides
org.gradle.configuration-cache=true

android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Stratégie d'exécution du compilateur Kotlin
kotlin.compiler.execution.strategy=daemon

# Allocation spécifique pour le daemon Kotlin
kotlin.daemon.jvm.options=-Xmx2048m

# Vos versions spécifiques
compose.compiler.kotlin.version=1.9.24
compose.compiler.version=1.5.12